title: probando los blogs de github
author: cayt
email: your-email@domain.com
description: > Aqui pondriamos el texto principal del blog

# social links
twitter_username: muerte a twitter
github_username:  cayt

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
